---
- name: Listen for webhook 8111 and Debug
  hosts: all
  sources:
  - ansible.eda.webhook:
      host: 0.0.0.0
      port: 8111
  rules:
  - name: Trigger action of scenario 1
    condition: >-
      event.payload.host_host == 'zabbix-agent-01'
      and event.payload.trigger_name == 'monitoring1_trigger1'
    action:
      run_job_template:
        name: Demo Workflow
        organization: Default
