---
- name: Listen for webhook 8111 from Zabbix
  hosts: all
  sources:
  - ansible.eda.webhook:
      host: 0.0.0.0
      port: 8111
  rules:
  - name: Trigger action of scenario 1
    condition: >-
      event.payload.host_host == 'zabbix-agent-01'
      and event.payload.trigger_name == 'monitoring1_trigger1'
    action:
      run_workflow_template:
        name: zabbix_eda_auto_response
        organization: Default
        job_args:
          extra_vars:
            z_host_name: "{{ event.payload.host_host }}"
            z_host_id: "{{ event.payload.host_id }}"
            z_event_id: "{{ event.payload.event_id }}"
            z_event_severity: "{{ event.payload.event_severity }}"
            z_trigger_name: "{{ event.payload.trigger_name }}"
